### ISSUE TITLE
Python 3.5 Clients don't work

### ISSUE THREAD

**Issue by Navotna** [pretenders/pretenders#119]
On ```SMTPMock('localhost', 8000)``` I got 
```
Traceback (most recent call last)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/smtp.py", line 12, in __init__
    super(SMTPMock, self).__init__(host, port)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 102, in __init__
    self.pretender_details = self._request_mock_access()
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 154, in _request_mock_access
    body=post_body)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 39, in http
    response = self._get_response(method, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 27, in _get_response
    self.connection.request(method=method, *args, **kwargs)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

on 
```
HTTPMock('localhost', 8000)
```
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/smtp.py", line 12, in __init__
    super(SMTPMock, self).__init__(host, port)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 102, in __init__
    self.pretender_details = self._request_mock_access()
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 154, in _request_mock_access
    body=post_body)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 39, in http
    response = self._get_response(method, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pretenders/client/__init__.py", line 27, in _get_response
    self.connection.request(method=method, *args, **kwargs)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

but running as standalone script works fine:
```
python -m pretenders.server.server --host 'localhost' --port 8000
```

**Comment by txels** [comment]
I guess you have closed the issue as you have realised that the `HTTPMock('localhost', 8000)` and equivalent SMTP create client instances that try to connect to a running server, whereas the *standalone script* you mention starts said server up.

I hope you have everything up and running now, and `pretenders` is proving to be a useful tool for your case.
