### ISSUE TITLE
HTTPMock doesn't work in Python 3.5

### ISSUE THREAD

**Issue by ghostsquad** [pretenders/pretenders#122]
```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pretenders.client.http import HTTPMock
>>> from pretenders.common.constants import FOREVER
>>> mock = HTTPMock('localhost', 8000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/http.py", line 49, in __init__
    super(HTTPMock, self).__init__(host, port, timeout, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/__init__.py", line 102, in __init__
    self.pretender_details = self._request_mock_access()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/__init__.py", line 156, in _request_mock_access
    pretender_details = json.loads(pretender_json)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ghostsquad** [comment]
Oh, somehow I missed first line in the example, that you have to start the server in a separate process. What is the recommended way to keep the server and test coupling tight? I'd like to run the server from with the test file, and the only thing I can think of to do so is by starting a subprocess async.

https://stackoverflow.com/questions/636561/how-can-i-run-an-external-command-asynchronously-from-python

**Comment by ghostsquad** [comment]
I was able to get a subprocess running in the background as the server, I can see the output from that, it seems working, but I'm still having lots of problems.

first simple thing is
```Python
>>> from pretenders.client.http import HTTPMock
>>> m = HTTPMock('localhost', 12346)
>>> m.when(u'GET /hello', 12346).reply(u'Hi!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/http.py", line 103, in reply
    self.preset.add(self.rule, status, body, headers, times, after)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/__init__.py", line 70, in add
    body=binary_to_ascii(response_body),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/common/http.py", line 46, in binary_to_ascii
    return base64.b64encode(data).decode('ascii')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/base64.py", line 62, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'
```

this is related to the reply string. I can encode the body, but I get:

```Python
>> from __future__ import unicode_literals
>>> utf8bytes = (u"test").encode('utf8')
>>> m.when(u'GET /hello', 12346).reply(utf8bytes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/http.py", line 103, in reply
    self.preset.add(self.rule, status, body, headers, times, after)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pretenders/client/__init__.py", line 80, in add
    raise ConfigurationError(data.decode())
pretenders.common.exceptions.ConfigurationError
```

**Comment by alexcouper** [comment]
Hi @ghostsquad apologies for taking so long to get back.

We currently only support up to 3.3 (see https://github.com/pretenders/pretenders/issues/113)

Could you try it out?

**Comment by txels** [comment]
Years have passed, we have revisited this repository, and we to only support Python >3.7 so I will close this issue.
